from typing import Any, Callable

class MetricsSnapshot:
    total_batches: int
    total_items: int
    flush_max_batch: int
    flush_deadline: int
    flush_manual: int

    def as_dict(self) -> dict[str, int]: ...

class BatcherCore:
    def __init__(self, max_batch: int, max_wait_ms: int, backpressure: str) -> None: ...
    def submit(self, item: Any, executor: Callable[[list[Any]], list[Any]]) -> Any: ...
    def flush(self) -> None: ...
    def metrics(self) -> MetricsSnapshot: ...
    def close(self) -> None: ...
